# Generated by Django 2.1.5 on 2019-03-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_aboutquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutquestion',
            old_name='times',
            new_name='time',
        ),
    ]
