# Generated by Django 2.1.7 on 2019-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('is_covered', models.BooleanField(default=False)),
            ],
        ),
    ]
