# Generated by Django 2.1.7 on 2019-03-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='access_modifier',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('POTECTED', 'POTECTED'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=8),
        ),
        migrations.AddField(
            model_name='questions',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_text',
            field=models.TextField(default=2.0),
            preserve_default=False,
        ),
    ]
