# Generated by Django 2.1.7 on 2019-03-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20190311_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='access_modifier',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_text',
        ),
    ]
