# Generated by Django 2.1.7 on 2019-03-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20190311_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=(1, 2, 3, 4, 5, 6, 7, 8, 9)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.TextField(default='Please describes your question..'),
        ),
    ]
