# Generated by Django 2.1.7 on 2019-03-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20190311_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='owner',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=(1, 2, 3, 4, 5, 6, 7, 8, 9)),
        ),
    ]
