# Generated by Django 2.1.5 on 2019-03-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20190318_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('course_number', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
                ('time', models.CharField(max_length=8)),
                ('total_questions', models.IntegerField(default=6)),
                ('to_be_answerd', models.IntegerField(default=4)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=(1, 2, 3, 4, 5, 6, 7, 8, 9)),
        ),
    ]
